exclude: "^data"
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
-   repo: local
    hooks:
    -   id: ruff
        name: ruff lint check
        entry: poetry run ruff check
        args: ["--fix"]
        language: system
        types: [python]
    -   id: ruff
        name: ruff format check
        entry: poetry run ruff format
        language: system
        types: [python]
    -   id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        pass_filenames: true
